"use client";

import React, { useEffect, useRef } from "react";
import Image from "next/image";
import gsap from "gsap";
import { ScrollTrigger } from "gsap/ScrollTrigger";

const Reviews = () => {

    const sectionRef = useRef<HTMLDivElement>(null);

    useEffect(() => {

        gsap.registerPlugin(ScrollTrigger);

        gsap.from(".slide", {
            x: -300,
            opacity: 0,
            duration: 1.2,
            stagger: 0.2,
            ease: "power3.out",
            scrollTrigger: {
                trigger: sectionRef.current,
                start: "top 80%",   // jab section viewport me aaye
                toggleActions: "play none none none"
            }
        });

    }, []);

    return (
        <section
            ref={sectionRef}
            className="w-full bg-black py-24 flex justify-center"
        >
            <div className="max-w-[1200px] w-full px-6">

                <h2 className="text-white text-4xl mb-12">
                    Journey Through Art of community
                </h2>

                <div className="grid grid-cols-4 gap-6 overflow-hidden">

                    <div className="slide col-span-2 h-[260px] relative rounded-xl overflow-hidden">
                        <Image src="/images/img3.webp" alt="" fill className="object-cover" />
                    </div>

                    <div className="slide h-[260px] relative rounded-xl overflow-hidden">
                        <Image src="/images/image2.webp" alt="" fill className="object-cover" />
                    </div>

                    <div className="slide h-[260px] relative rounded-xl overflow-hidden">
                        <Image src="/images/img4.webp" alt="" fill className="object-cover" />
                    </div>

                    <div className="slide h-[260px] relative rounded-xl overflow-hidden">
                        <Image src="/images/img1.jpg" alt="" fill className="object-cover" />
                    </div>

                    <div className="slide flex flex-col justify-center items-center bg-[#111] rounded-xl h-[260px]">
                        <h3 className="text-lime-400 text-3xl font-semibold">48,000</h3>
                        <p className="text-gray-400 text-sm text-center mt-2 px-4">
                            Images generated by Artificial Intelligence
                        </p>
                    </div>

                    <div className="slide col-span-2 h-[260px] relative rounded-xl overflow-hidden">
                        <Image src="/images/img5.jpeg" alt="" fill className="object-cover" />
                    </div>

                </div>
            </div>
        </section>
    );
};

export default Reviews;